In [5]:
pd.Series([30, 35, 40], index = ['2015 Sales', '2016 Sales', '2017 Sales'], name = 'Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [6]:
pd.DataFrame({'Apples': ['20'],
              'Bananas': ['21']},
              index = [0])

  Apples Bananas
0     20      21

In [12]:
Fruit_Sales = pd.DataFrame({'Apples': ['35','41'],
             'Bananas': ['21','34']},
             index = ['2017 Sales', '2018 Sales'])

In [4]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
pd.Series(['4 cups', '1 cup', '2 large', '1 can'],
          ['Flour', 'Milk', 'Eggs', 'spam'],
          name = 'Dinner', dtype = 'object')

Flour     4 cups
Milk       1 cup
Eggs     2 large
spam       1 can
Name: Dinner, dtype: object

In [16]:
pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [9]:
pd.DataFrame({'Bob': ['I like it', 'it was aweful'],
              'Sue': ['pretty good', 'Bland.']},
              index = ['Product A', 'Product b'])

                     Bob          Sue
Product A      I like it  pretty good
Product b  it was aweful       Bland.

In [ ]:
pd.DataFrame({'Bob': ['i like it', 'it was aweful'], 'sue': ['pretty good', 'bland']})

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

In [8]:
import pandas as pd
print(pd.__version__)

3.0.6